---
version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push docker image
          command: |
            cp Makefile CustomMakefile
            sed "s/phusion/johnsonch/g" CustomMakefile > Makefile
            make all


workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - latest_rvm_support
